### ISSUE TITLE
アルゴリズム課題_探索

### ISSUE THREAD

**Issue by shuheiokuda0704** [as-shimizu/OJT_JavaScript#15]
数値列から指定の値を探し出す探索アルゴリズムを用いて、アルゴリズム学習します。

探索にはいくつかアルゴリズムがあります。
その中からアルゴリズムの学習によく使われる、
線形探索、2分探索を実装し、各処理の時間を比較します。(※参考1)
また、JavaScript の探索メソッド(※参考2)もあるので、それと処理時間を比較してみましょう。
参考1 : https://tech-camp.in/note/1050/#i-3
参考2 : https://www.softel.co.jp/blogs/tech/archives/1377

想定時間：5時間。5時間で収まるように仕様は調整してもらって良いです。

仕様 :
　必須 : 入力の数値列(整数)に対して、探索を行う
　　　   各探索アルゴリズムでの処理時間をわかるようにする
　　　   最大値、最小値を探索できるようにする
　任意 : 入力する数値列の長さは可変
　　　   数値列の入力方法は任意(ブラウザ上でテキストで入力しても、CSV でファイルから読み込んでも良い)

**Comment by as-shimizu** [comment]
ファイル選択でファイルを選択しないと検索、最大値、最小値のボタンは機能しません。（"ファイルを選択してください"などのメッセージは表示されない仕様です。）
2分探索は、データが昇順に並んでる時に使用できます。
