### ISSUE TITLE
Ch5_じゃんけん_option に手の表示機能追加

### ISSUE THREAD

**Issue by shuheiokuda0704** [as-shimizu/OJT_JavaScript#18]
手を選んだら、勝った負けただけ言われるけど、実感がない。
自分の手を選んだら自分の手と相手の手を表示してくれたほうがわかりやすくていい。
さらに自分の手を表示してから、一拍置いて相手の手を出してくれたほうがゲーム感あるかも

**Comment by as-shimizu** [comment]
#13 で実装済み
